---
appid: usnistgov.sbgui.v1.1.0
arduino:
  flag1pins:
    f5: 5
    f6: 6
    f7: 7
    f8: 8
  port: COM4
  uvpins:
    in: 13
    out: 12
camera:
  cam0:
    checked: false
    diag: 1
    flag1: 8
    fps: 120
    name: Basler camera
    previewFPS: 15
    recFPS: 30
    type: bascam
  cam1:
    checked: false
    diag: 1
    flag1: 9
    fps: 15
    name: Nozzle camera
    previewFPS: 15
    recFPS: 15
    type: webcam
  cam2:
    checked: false
    diag: 1
    flag1: 10
    fps: 15
    name: Webcam 2
    previewFPS: 15
    recFPS: 15
    type: webcam
convert:
  addToQueue: true
  closeWhenDone: false
  gcodeFolder: C://
  sameFolder: false
  sbpFolder: C://
files:
  createSubfolders: true
  dateFormat: '%y%m%d'
  duplicateFormat: '{0:0=3d}'
  includeDateRadio: 0
  includeSBInFile: true
  includeSBRadio: 1
  includeSampleInFile: true
  includeSampleInFolder: true
  includeTimeInFile: true
  save: C://
  separator: _
  tag: test
  timeFormat: '%y%m%d_%H%M%S_%f'
fluigent:
  channel0:
    calibration:
      flowRateFolder: C://
      initDensity: 1
      initDiam: 0.603
      initSpeed: 40.0
    color: '#3f8d88'
    flag1: 5
  channel1:
    calibration:
      flowRateFolder: C://
      initDensity: 1
      initDiam: 0.603
      initSpeed: 5.0
    color: '#b0401e'
    flag1: 6
  dt: 50
  pmax: 6000
  savePressure: true
  trange: 60
  units: mbar
layout:
  save: true
meta:
  camera_magnification:
    units: x
    value: '0.5'
  camera_position:
    units: None
    value: side
  nozzle_inner_diameter:
    units: mm
    value: '0.603'
  nozzle_length:
    units: mm
    value: '38'
  nozzle_material:
    units: None
    value: stainless steel
  nozzle_outer_diameter:
    units: mm
    value: '0.908'
  tubing_inner_diameter:
    units: mm
    value: '0.79375'
  tubing_length:
    units: mm
    value: '280'
  tubing_material:
    units: None
    value: PTFE
savePressure: true
shopbot:
  autoplay: false
  burstLength: 
      value: 0
      units: mm
  burstScale: 1.0
  critTimeOff: 
      value: 0
      units: s
  critTimeOn: 
      value: 0
      units: s
  currentFile: No file selected
  diag: 2
  dt: 
    units: ms
    value: 10.0
  flag1: 4
  flag1max: 12
  flag1min: 1
  includeFlagInTable: true
  includePositionInTable: true
  runSimple: 2
  saveDt: 
    units: ms
    value: 25
  savePicMetadata: true
  sbpFiles: 
  - No file selected
  sbpFolder: C://
  showFolder: false
  units: mm
  zeroDist: 0.1
testFolder: C://
uv:
  flag1: 7
  color: '#4e1263'
  